contest/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^(?P<contest_id>\d+)/$', views.contest_view, name='contest_view'),
    url(r'^prob_upload/$', views.prob_upload, name='prob_upload'),
    url(r'^problem/(?P<problem_id>\d+)/$', views.problem_view, name='problem'),

]

cstadium/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^leaderboard/', include('leaderboard.urls', namespace='leaderboard')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^contest/', include('contest.urls', namespace='contest')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^checker/', include('checker.urls', namespace='checker'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.home_view, name='home_view'),
]

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from contest.models import Contest
from userprof.models import UserProfile


def home_view(request):
    all_contests = Contest.objects.all()
    return render(request, 'home/home_view.html', {'all_contests': all_contests, })

templates/home/home_view.html
{% extends "base/site_base.html" %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/home_view.css' %}">
<link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
{% endblock %}


{% block content %}
<br><br><br>
<div class="container">
<div class="row">
	{% for contest in all_contests %}
		<div class="col s12 m6 l4 ">
          <div class="card hoverable yellow darken-1 z-depth-5">
            <div class="card-content black-text">
              <span class="card-title"><strong>{{ contest.name_of_contest }}</strong>
              {% if contest.live == True %}
                   <div class="led-green"></div>
              {% else %}
              		<div class="led-red"></div>
              {% endif %}	
              </span>
              <p>This is a <strong>{% if contest.rated_or_not %}rated{% else %}test(unrated){% endif %}</strong> contest.<br> This challenge is designed to test 
              your algorithmic/mathematical thinking.<br>
              <div class="contest_info">
	              Total number of problems:{{ contest.number_of_problems }}
	              <br> Total time allotted:{{ contest.duration_of_content }} hrs.
              </div>
              </p>
            </div>
            <div class="card-action blue-grey">
              <a href="{% url 'contest:contest_view' contest_id=contest.contest_id %}" >Go to contest</a>
              <a >Rank :</a>
            </div>
          </div>
        </div>
    {% endfor %}
</div>
</div>
{% endblock %} 