checker/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^problem/submit/(?P<problem_id>\d+)',
        views.solution_submit, name='solution_submit'),

]

contest/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^(?P<contest_id>\d+)/$', views.contest_view, name='contest_view'),
    url(r'^prob_upload/$', views.prob_upload, name='prob_upload'),
    url(r'^problem/(?P<problem_id>\d+)/$', views.problem_view, name='problem'),

]

cstadium/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^leaderboard/', include('leaderboard.urls', namespace='leaderboard')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^contest/', include('contest.urls', namespace='contest')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^checker/', include('checker.urls', namespace='checker'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.home_view, name='home_view'),
]

contest/models.py
from __future__ import unicode_literals
from django.db import models

from userprof.models import UserProfile
from tinymce.models import HTMLField
from tinymce.widgets import TinyMCE
from ckeditor.fields import RichTextField

import os

# Create your models here.


class Contest(models.Model):
    contest_id = models.IntegerField(unique=True)
    name_of_contest = models.CharField(max_length=20)
    rated_or_test = models.BooleanField(default=False)
    number_of_problems = models.IntegerField(default=0)
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    duration_of_content = models.FloatField(default=0)
    live = models.BooleanField(default=False)

    def __str__(self):
        return self.name_of_contest


def test_file_upload(instance, filename):
    # file will be uploaded to MEDIA_ROOT/<problem_id>/<filename>
    return 'problems/problem_{0}/{1}'.format(instance.problem_id, filename)


def sample_io_upload(instance, filename):
    return 'problem_{0}/{1}'.format(instance.problem_id, filename)


class Problem(models.Model):
    problem_id = models.IntegerField(primary_key=True)
    name_of_problem = models.CharField(unique=True, max_length=40)
    test_files = models.FileField(upload_to=test_file_upload, null=True)
    statement = RichTextField()
    contest = models.ForeignKey(Contest, null=True, related_name='problems')
    time_limit = models.IntegerField(default=1)
    max_score = models.IntegerField(default=100)
    number_of_correct_submissions = models.IntegerField(default=0)
    solved_by_whom = models.ManyToManyField(UserProfile,)

    def __str__(self):
        return self.name_of_problem

contest/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Problem

from ckeditor.fields import RichTextField


class ProblemText(forms.ModelForm):
    class Meta:
        model = Problem
        fields = ['statement']
        labels = {
            'statement': _(''),
        }

contest/views.py
import zipfile
import os

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.files.base import File

from .models import Contest, Problem
from .forms import ProblemText
from userprof.models import UserProfile


id_error = ""
title_error = ""
file_error = ""


def validate_form(request):
    global id_error
    global title_error
    global file_error

    try:
        prob_obj1 = Problem.objects.get(
            problem_id=request.POST.get('problem_id'))
    except:
        prob_obj1 = None

    try:
        prob_obj2 = Problem.objects.get(
            name_of_problem=request.POST.get('problem_title'))
    except:
        prob_obj2 = None

    if prob_obj1 is not None:
        id_error = "This problem id already exists"
    if prob_obj2 is not None:
        title_error = "This problem title already exists"
    if (zipfile.is_zipfile(request.FILES['test_files'])) == False:
        file_error = "Uploaded Filetype is not zip"

    if ((prob_obj1 is None) and (prob_obj2 is None) and
            ((zipfile.is_zipfile(request.FILES['test_files'])) == True)):
        return True

    return False


def contest_view(request, contest_id):
    user_obj = UserProfile.objects.get(user=request.user)
    contest_obj = Contest.objects.get(contest_id=contest_id)
    all_problems = contest_obj.problems.all
    return render(request, 'contest/contest_view.html',
                  {'contest_obj': contest_obj, 'all_problems': all_problems, 'user_obj': user_obj, })


def prob_upload(request):
    global id_error
    global title_error
    global file_error

    submitted = None
    all_contests = Contest.objects.all
    problem_obj = Problem()
    form = ProblemText()

    if request.method == "POST":
        contest_obj = Contest.objects.get(
            name_of_contest=request.POST.get('contest_dropdown'))
        zipped_file = request.FILES['test_files']

        if validate_form(request) == True:

            submitted = True
            problem_obj = Problem(problem_id=request.POST.get('problem_id'),
                                  name_of_problem=request.POST.get(
                                      'problem_title'),
                                  max_score=request.POST.get('max_score'),
                                  time_limit=request.POST.get('time_limit'),
                                  contest=contest_obj,
                                  test_files=zipped_file,
                                  statement=request.POST.get('statement'),
                                  )
            problem_obj.save()
            unzipped_file = zipfile.ZipFile(zipped_file)
            p_id = request.POST.get('problem_id')
            i = 0
            path_to_save = os.path.dirname(
                os.path.dirname(os.path.abspath(__file__)))
            path_to_save = os.path.join(
                path_to_save, 'media/problems/problem_' + str(p_id))
            print path_to_save
            print "save_dir " + os.path.join(path_to_save, 'input')
            os.makedirs(os.path.join(path_to_save, 'input'), 0755)
            os.makedirs(os.path.join(path_to_save, 'output'), 0755)

            for item in unzipped_file.namelist():
                if i <= 4:
                    file_ = file(path_to_save + '/input/input0' + str(i) +
                                 '.txt', 'w').write(unzipped_file.read(item))
                else:
                    file_ = file(path_to_save + '/output/output0' +
                                 str(i - 5) + '.txt', 'w').write(unzipped_file.read(item))

                i += 1
        else:
            submitted = False

    return render(request, 'contest/problem_view.html', {'all_contests': all_contests,
                                                         'submitted': submitted,
                                                         'id_error': id_error,
                                                         'title_error': title_error,
                                                         'file_error': file_error,
                                                         'problem_obj': problem_obj,
                                                         'form': form,
                                                         })


def problem_view(request, problem_id):
    problem_obj = Problem.objects.get(problem_id=problem_id)

    return render(request, 'contest/problem_statement.html', {'problem_obj': problem_obj})

templates/contest/contest_view.html
{% extends "base/site_base.html" %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/conteststyle.css' %}">
{% endblock %}


{% block content %}

	<div id="demo">
  <center><h1>Algorithmic Contest</h1></center><br>
  
  <!-- Responsive table starts here -->
  <!-- For correct display on small screens you must add 'data-title' to each 'td' in your table -->
  <div class="table-responsive-vertical shadow-z-5">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
      <thead>
        <tr>
          <th>ID</th>
          <th>Problem</th>
          <th>Submissions</th>
          <th>Max Score</th>
        </tr>
      </thead>
      <tbody>

			{% for problem in all_problems %}
				<tr>
					<td data-title="ID" >{{ problem.problem_id }} </td>
					<td data-title="Problem"> <a href="{% url 'contest:problem' problem.problem_id %}">{{ problem.name_of_problem }}</a> </td>
					<td data-title="Submissions"> {{ problem.number_of_correct_submissions }}</td>
					<td data-title="Max Score" > {{ problem.max_score }}</td>		 
				</tr>		
			{% endfor %}

      </tbody>
    </table>
  </div>
 </div>

{% endblock %}

templates/contest/pp.html
{% extends "base/site_base.html" %}
{% load static %}
{% load tinymce_tags %}
{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/problem_view.css' %}">
{% endblock %}

{% block navbar %}{% endblock %}


{% block content %}

	<div style="position: absolute;" >
	   {% if submitted == False %}
	   		<div class="black">
	       	<p class="red-text " > Problem wasn't uploaded due to the following reasons </p>
	       	<ul>
	       		<li class="white-text" >{{ id_error }}</li>	
	       		<li class="white-text" >{{ title_error }}</li>
	       	</ul>
	       	</div>
	   {% elif submitted == True %}
	       	<p id="mess" class="green-text">Problem uploaded successfully</p>
	   {% endif %}
	</div>








<form id="prob_upload" method="post" action="{% url 'contest:prob_upload' %}" enctype="multipart/form-data"
 novalidate="novalidate">
	{% csrf_token %}
	{% load static %}
	<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
	<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

 <div class="row">
    	 <div class="row">
	        <div class="col s12">
	          <div class="input-field inline">
	            <input  name="problem_id" id="problem_id" type="number" class="validate">
	            <label for="problem_id" data-error="{{ id_error }}" data-success="right">Problem ID</label>
	          </div>
	          <div class="input-field inline">
	            <input  name="problem_title" id="problem_title" type="text" class="validate">
	            <label for="problem_title" data-error="provide " data-success="right">Problem Title</label>
	          </div>

	        </div>
	      </div>
	      
		<div class="input-field col s12">
			<div class="file-field input-field">
			      <div class="btn">
			        <span>Test Cases</span>
			        <input name="test_files" type="file">
			      </div>
			      <div class="file-path-wrapper">
			        <input  class="file-path validate" type="text">
			      </div>
		    </div>
		    <br>
		    <select name="contest_dropdown">
		      <option value="" disabled selected>Contest</option>
			      {% for contest in all_contests %}
				      <option value="{{ contest.name_of_contest }}">{{ contest.name_of_contest }}</option>
			      {% endfor %}
		    </select> <br>
		</div>

		

    	  <div class="row">
	        <div class="col s12">
	          <div class="input-field inline">
	            <input min="1"  name="max_score" id="max_score" type="number" class="validate">
	            <label for="max_score" data-error="The score cannot be less than 1" data-success="right">Max Score</label>
	          </div>

	          <div class="input-field inline">
	            <input  max="10"  name="time_limit" id="time_limit" type="number" class="validate">
	            <label for="time_limit" data-error="Time limit cannot exceed 10 seconds" >Time Limit</label>
	          </div>
	           <p><strong>Statement</strong> </p>
	  	      	<div style="position: relative; right: 100px;">
					{{ form.as_p }}  
				</div>

	          <button style="display: block" class="btn waves-effect waves-light" type="submit" name="action">Submit
				    <i class="material-icons right">send</i>
			    </button>

	        </div>
	      </div>
  </div>
</form>




	      




<script type="text/javascript">
	 $(document).ready(function() {
    $('select').material_select();
  });

   $('#mess').delay(3000).fadeOut(5000);


</script>





{% endblock %}

templates/contest/problem_statement.html
{% extends "base/site_base.html" %}
{% load static %}

{% block extra_head %}
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/problem_statement.css' %}">
{% endblock %}

{% block body_class %} backg {% endblock %}

{% block content %}
asd
<div class="container">
	  <div class="row valign-wrapper">
	    <div class="col s12 m12 l12   valign">
	      <div class="card  darken-1">
	        <div class="card-content black-text">
	          <span class="card-title blue-text text-darken-2"><strong>{{ problem_obj.name_of_problem }}</strong>  </span>
	      	  <span class="extra_info" >Time limit:<div class="info_text">  {{ problem_obj.time_limit }} sec </div>  </span>
	      	  <span class="extra_info" > Maximum Score:<div class="info_text"> {{ problem_obj.max_score }}</div> </span>
	      	  <span class="extra_info" > Solved by:<div class="info_text"> {{ problem_obj.number_of_correct_submissions }}</div> </span>	      	  	
	        </div>
	      </div>
	    </div>
	  </div>
</div>      
	      


	<div class="container">
	  <div class="row valign-wrapper">
	    <div class="col s12 m12 l12   valign">
	      <div class="card  darken-1">
	        <div class="card-content black-text">
	          <p style="font-family: 'Open Sans', sans-serif;" >
	          	{{ problem_obj.statement | safe }}
	          </p>
	        </div>
	      </div>
	    </div>
	  </div>
	</div>

	<div class="container">
	  <div class="row valign-wrapper">
	    <div class="col s12 m12 l6"  >
	      <div class="card  darken-1">
	        <div class="card-content black-text">
	          <p style="font-family: 'Open Sans', sans-serif;" class="hei" >
	          Sample Input<br><br> 	     
	          <code class="blue-text darken-3">
	           	5 <br>
	          	1 2 3 4 5
	           </code>
	          	
	          </p>
	        </div>
	      </div>
	    </div>
	      
	    <div class="col s12 m12 l6" >
	      <div class="card  darken-1">
	        <div class="card-content black-text">
	          <p style="font-family: 'Open Sans', sans-serif;" class="hei" >
	          Sample Output<br><br>
	          <code class="blue-text darken-3" >
	          	4
	          </code>
	          </p>
	        </div>

	      </div>

	    </div>
	  </div>


	  <!-- Modal Trigger -->
  <a class="waves-effect waves-light btn green" href="#modal1">Upload</a>



  <!-- Modal Structure -->
	  <div id="modal1" class="modal">
	    <div class="modal-content">
	      <h4>Select Code</h4>
			 <form id="sol_upload" method="post" action="{% url 'checker:solution_submit' problem_id=problem_obj.problem_id %}" 
	      enctype="multipart/form-data" novalidate="novalidate">
	      		{% csrf_token %}
			    <div class="file-field input-field">
			      <div class="btn green">
			        <span>File</span>
			        <input name="code_upload" type="file">
			      </div>
			      <div class="file-path-wrapper">
			        <input class="file-path validate" type="text" style="width: 50%;" >
			      </div>
			    </div>

			    <button  class="btn waves-effect waves-light" type="submit" name="action" >Upload
				    <i class="material-icons right">send</i>
		      </button>
			 </form>
	    </div>
	  </div>



	          
</div>	    

      

<script type="text/javascript">
	 $(document).ready(function(){
    // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
    $('.modal').modal();
  });
</script>
	 
{% endblock %}


        
	        




	      

	      

templates/contest/problem_view.html
{% extends "base/site_base.html" %}
{% load static %}
{% load tinymce_tags %}
{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/problem_view.css' %}">
{% endblock %}

{% block navbar %}{% endblock %}


{% block content %}

	<div style="position: absolute; top: 0%;" >
	   {% if submitted == False %}
	   		<div class="black">
	       	<p class="red-text " > Problem wasn't uploaded due to the following reasons </p>
	       	<ul>
	       		<li class="white-text" >{{ id_error }}</li>	
	       		<li class="white-text" >{{ title_error }}</li>
	       		<li class="white-text" >{{ file_error }}</li>
	       	</ul>
	       	</div>
	   {% elif submitted == True %}
	       	<p id="mess" class="green-text">Problem uploaded successfully</p>
	   {% endif %}
	</div>


<form id="prob_upload" method="post" action="{% url 'contest:prob_upload' %}" enctype="multipart/form-data"
 novalidate="novalidate">
	{% csrf_token %}
	{% load static %}
	<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
	<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

 <div class="row">

 		<!-- <div  class="hell1"> -->
    	 <div class="row">
	        <div class="col s12">
	          <div class="input-field inline">
	            <input  name="problem_id" id="problem_id" type="number" class="validate">
	            <label for="problem_id" data-error="{{ id_error }}" data-success="right">Problem ID</label>
	          </div>
	          <div class="input-field inline">
	            <input  name="problem_title" id="problem_title" type="text" class="validate">
	            <label for="problem_title" data-error="provide " data-success="right">Problem Title</label>
	          </div>

	        </div>
	      </div>
	      
		<div class="input-field col s12">
			<div class="file-field input-field">
			      <div class="btn">
			        <span>Test Cases</span>
			        <input name="test_files" type="file">
			      </div>
			      <div class="file-path-wrapper">
			        <input  class="file-path validate" type="text">
			      </div>
		    </div>
		    <br>
		    <select name="contest_dropdown">
		      <option value="" disabled selected>Contest</option>
			      {% for contest in all_contests %}
				      <option value="{{ contest.name_of_contest }}">{{ contest.name_of_contest }}</option>
			      {% endfor %}
		    </select> <br>
		</div>

		

    	  <div class="row">
	        <div class="col s12">
	          <div class="input-field inline">
	            <input min="1"  name="max_score" id="max_score" type="number" class="validate">
	            <label for="max_score" data-error="The score cannot be less than 1" data-success="right">Max Score</label>
	          </div>

	          <div class="input-field inline">
	            <input  max="10"  name="time_limit" id="time_limit" type="number" class="validate">
	            <label for="time_limit" data-error="Time limit cannot exceed 10 seconds" >Time Limit</label>
	          </div>

			</div>
		   </div>	
		   </div>

		  <div class="hell2" > 
		   <div class="row">
	        <div class="col s12">      
	           <p><strong>Statement</strong> </p>
	  	      	<div style="position: relative; right: 100px;">
					{{ form.as_p }}  
				</div>

	          <button style="display: block" class="btn waves-effect waves-light" type="submit" name="action">Upload
				    <i class="material-icons right">send</i>
		      </button>

	        </div>
	      </div>
	     </div> 
  </div>
</form>


<script type="text/javascript">
	 $(document).ready(function() {
    $('select').material_select();
  });

   $('#mess').delay(3000).fadeOut(5000);


</script>





{% endblock %}